version: '3' 
services:
  atom-docker:
    image: openkbs/atom-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atom-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.atom:/home/developer/.atom
      - ./workspace:/home/developer/workspace

